kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: slackbot-kyube
  labels:
    app: slackbot-kyube
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - slackbot-kyube
        from:
          kind: ImageStreamTag
          namespace: yy-demo-project
          name: 'slackbot-kyube:latest'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: slackbot-kyube
    deploymentconfig: slackbot-kyube
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: slackbot-kyube
        deploymentconfig: slackbot-kyube
    spec:
      containers:
        - name: slackbot-kyube
          image: "slackbot-kyube:latest"
          envFrom:
          - secretRef:
              name: slackbot-secret-kyube

