apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: slackbot-kyube
  name: slackbot-kyube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slackbot-kyube
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: slackbot-kyube
    spec:
      containers:
      - name: slackbot-kyube
        image: ysuke25r/kyube:1.0
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: slackbot-secret-kyube
